### ISSUE TITLE
Model 만들기

### ISSUE THREAD

**Issue by lingostar** [DevLuce/NatureUp#19]
https://github.com/DevLuce/NatureUp/blob/2886c887f16c0c51f0b7be191e64451b39047ff8/NatureUp/Views/Home/ActivityList.swift#L33-L35

데이터 구조를 잡아야 할 때군요.

데이터 구조는 뷰의 구성과는 달리
'Activity' 라는 구조체 안의 속성으로 '실내'와 '야외'를 넣고
뷰에 뿌릴 때 구분해서 뿌리는 방식으로 하는 게 좋지 않을까요?

**Comment by DevLuce** [comment]
좋은 말씀 감사합니다! 해당 뷰를 AcitivityRow라는 구조체로 바꾸고 Activity 모델을 만들어 뿌리는 방식으로 정정하였습니다.
