### ISSUE TITLE
HomeView 수정부탁드려요

### ISSUE THREAD

**Issue by JungYunseong** [DevLuce/NatureUp#4]
**MyStatus**

- [x] Divider 길이 수정

**Activity**

- [x] Stroke 색상변경 (red: 151.0/255, green: 151.0/255, blue: 151.0/255)

- [x] NavigationLink(destination: AuthenticationView) 추가

**HomeView**

- [x] 랜덤평가 진행하기 Button Stroke 제거

수정 부탁드려요

**Comment by DevLuce** [comment]
해결했습니다 감사합니다.
