### ISSUE TITLE
LeaderBoard 페이지로 이동시 NavigationBar가 사라지는 오류 수정 부탁드립니다.

### ISSUE THREAD

**Issue by DevLuce** [DevLuce/NatureUp#48]
![화면-기록-2022-04-12-오후-3 59 46](https://user-images.githubusercontent.com/56063805/162900152-dc323c1d-375d-4584-82ef-1e4c4995a743.gif)

- [ ] NavigationBar 사라지는 오류 수정

**Comment by Shin-jun** [comment]
해결했습니다 #49  감사합니다. @DevLuce
