### ISSUE TITLE
CameraView 사용 후 홈으로 Dismiss 한 이후에 생기는 카메라 불능 버그

### ISSUE THREAD

**Issue by DevLuce** [DevLuce/NatureUp#52]
https://user-images.githubusercontent.com/56063805/162908290-24ef118a-3e4a-448e-970e-df87365678c4.MP4

위 영상과 같이 상세 페이지에서는 dismiss 이후에도 카메라가 잘 작동합니다. 하지만 홈으로 dismiss 한 이후에는 카메라가 작동하지 않습니다.

https://user-images.githubusercontent.com/56063805/162908048-8bfc55a9-9e58-4aa5-859d-362c9f8b9a97.MP4

마찬가지로 홈 화면에서 보여지는 3개 목록에서 인증을 한 후에 홈으로 dismiss 한 이후에도 카메라가 작동하지 않습니다. 

도와주세요 @lingostar @unnnyong

**Comment by JungYunseong** [comment]
버그 수정하였습니다
